### ISSUE TITLE
Multiple services of type PHPStan\Rules\PHPUnit\CoversHelper found error since phpstan-phpunit  >1.2.0

### ISSUE THREAD

**Issue by samsonasik** [phpstan/phpstan-phpunit#142]
Since >1.2.0, it seems there is error in `rector-src`:

```bash
PHP Fatal error:  Uncaught _PHPStan_71ced81c9\Nette\DI\ServiceCreationException: Multiple services of type PHPStan\Rules\PHPUnit\CoversHelper found: 0293, 0305 in phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Autowiring.php:53
Stack trace:
#0 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/ContainerBuilder.php(170): _PHPStan_71ced81c9\Nette\DI\Autowiring->getByType('PHPStan\\Rules\\P...', true)
#1 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php(312): _PHPStan_71ced81c9\Nette\DI\ContainerBuilder->getByType('PHPStan\\Rules\\P...', true)
```

For both 1.2.0 and 1.2.1

I currently pin to 1.1.3 : https://github.com/rectorphp/rector-src/pull/3018

/cc @TomasVotruba to keep track.

**Comment by ondrejmirtes** [comment]
I have an idea where the problem comes from in Rector codebase. And I found out by accident a few days ago when I implemented this feature: https://github.com/phpstan/phpstan-src/commit/f15cd6deea2dda4b41272aa50fb3b61304ad3515

In this form it made Rector failed in multiple places with this stack trace:

```
68) Rector\Tests\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector\ReturnTypeDeclarationRectorTest::test with data set #66 ('/home/runner/work/phpstan/php...hp.inc')
PHPStan\DependencyInjection\DuplicateIncludedFilesException: These files are included multiple times: /home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/phpstan/phpstan-phpunit/extension.neon, /home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/phpstan/phpstan-webmozart-assert/extension.neon

phar:///home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php:174
phar:///home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/ContainerFactory.php:85
/home/runner/work/phpstan/phpstan/e2e/integration/repo/packages/NodeTypeResolver/DependencyInjection/PHPStanServicesFactory.php:50
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1045
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:567
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1164
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1015
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:567
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1164
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1114
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1026
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:567
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1164
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1114
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1026
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:567
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1164
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1114
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1114
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1026
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:567
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1164
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1114
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1026
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:567
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1164
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1114
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1026
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:567
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1164
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1114
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1026
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:567
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1164
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1114
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:1026
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:567
/home/runner/work/phpstan/phpstan/e2e/integration/repo/vendor/symfony/dependency-injection/ContainerBuilder.php:512
/home/runner/work/phpstan/phpstan/e2e/integration/repo/packages/Testing/PHPUnit/AbstractTestCase.php:61
/home/runner/work/phpstan/phpstan/e2e/integration/repo/packages/Testing/PHPUnit/AbstractRectorTestCase.php:55
```

So I made it optional: https://github.com/phpstan/phpstan-src/commit/4cdb8060b73fc09e25cf230041532f068974234d

The problem probably is that you include `phpstan-phpunit` configuration in both `phpstan-for-rector.neon` config file, and globally in `Rector\NodeTypeResolver\DependencyInjection\PHPStanServicesFactory::resolveExtensionConfigs()`.

**Comment by samsonasik** [comment]
@ondrejmirtes Thank you, that seems solve it, I will create PR to rector-src and let's see if it resolve it by remove from phpstan-for-rector.neon:

```diff
--- a/phpstan-for-rector.neon
+++ b/phpstan-for-rector.neon
@@ -12,4 +12,3 @@ parameters:
 # load extension
 includes:
     - vendor/phpstan/phpstan-webmozart-assert/extension.neon
-    - vendor/phpstan/phpstan-phpunit/extension.neon
```

**Comment by ondrejmirtes** [comment]
I think a better solution would be to disable the discovery of extensions for tests altogether.

Because your suggestion just postpones the problem, but it's gonna happen again.

**Comment by samsonasik** [comment]
@ondrejmirtes that's probably a bc break for disable extension discovery

@TomasVotruba to decide

I will close it for now as it seems https://github.com/rectorphp/rector-src/pull/3020 is green. 

Thank you @ondrejmirtes for the help.
